package com.hostel.entity;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,

    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,

    STUDENT_CREATED,
    STUDENT_UPDATED,
    STUDENT_DELETED,

    WARDEN_CREATED,
    WARDEN_UPDATED,
    WARDEN_DELETED,

    HOSTEL_CREATED,
    HOSTEL_UPDATED,

    BLOCK_CREATED,
    BLOCK_UPDATED,

    ROOM_CREATED,
    ROOM_UPDATED,
    ROOM_ALLOCATED,
    ROOM_TRANSFERRED,
    ROOM_VACATED,

    LEAVE_APPLIED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,

    COMPLAINT_CREATED,
    COMPLAINT_UPDATED,
    COMPLAINT_RESOLVED,
    COMPLAINT_REOPENED,

    NOTICE_CREATED,
    NOTICE_UPDATED,
    NOTICE_DELETED,

    MESS_FEEDBACK_SUBMITTED,

    LOST_ITEM_REPORTED,
    FOUND_ITEM_REPORTED,

    MARKETPLACE_ITEM_CREATED,
    MARKETPLACE_ITEM_UPDATED,
    MARKETPLACE_ITEM_DELETED
}
